### ISSUE TITLE
SDXL not working

### ISSUE THREAD

**Issue by jwooldridge234** [Nekos4Lyfe/TokenMixer#3]
This looks like a really cool extension- thanks! Works fine for SD1.5, but I'm trying to run it with an SDXL model and I get this error:

```python
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/scripts/main.py", line 15, in <module>
        from lib.modules.token_mixer import TokenMixer
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/modules/token_mixer.py", line 15, in <module>
        from lib.data import dataStorage
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/data.py", line 768, in <module>
        dataStorage = Data() #Create data
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/data.py", line 748, in __init__
        Data.tools = Tools()
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/toolbox/tools.py", line 129, in __init__
        self.tokenizer , self.internal_embs , self.loaded_embs = self.get()
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/toolbox/tools.py", line 59, in get
        elif self.is_sdxl : internal_emb_dir = embedder.roberta.embeddings # SDXL :Check if this works
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'Module' object has no attribute 'roberta'
``` 

It looks like it's line 59 of tools.py "elif self.is_sdxl : internal_emb_dir = embedder.roberta.embeddings" that's causing the issue. I poked around in sd_models_xl.py and sd_hijack.py and logged the hijack def since that's where SDXL gets its cond_stage_model from - looks like it's using the FrozenCLIPEmbedderForSDXLWithCustomWords section (line 194) and not the FrozenXLMREmbedderWithCustomWords (line 214). I'm happy to help debug but I'm not sure quite where to go from here.

EDIT: This is using Automatic1111's UI.

**Comment by Nekos4Lyfe** [comment]
Hey thanks for the help! I haven't gotten to debugging with SDXL yet. 

I'm still waiting for the major A1111 update that will solve the current VRAM issues when running SDXL. Last time I tried (about 2 weeks ago) I couldn't even get SDXL to run on my device.  

I decided to leave it at that and make a new attempt once the ongoing compatibility issues between A1111 and SDXL had "settled down" so-to-speak. 

As a consequence, the code written on line 59 and 62 are pure guesswork on my end. You can see the comment in the code below. 

![SDXL compatibility](https://github.com/Nekos4Lyfe/TokenMixer/assets/130230016/055b65d4-3cba-46ef-8f13-dcca73657aad)

If you can get line 59 to work, the TokenMixer should be good-to-go with SDXL.  There shouldn't be any other compatibility issues other than what you find in "Tools.py" .

(can't make any promises for "cross_attention_mixer.py"  though as I am not the author of that code, but you can disable that module in the main.py folder should it prove to be incompatible with SDXL )

That is all the help I can provide at this moment.

Once I get SDXL to work on my own device I can debug this issue, but I can't promise the update will come in a timely manner as I am not particularly incentivized to use SDXL on A1111 yet.

**Comment by jwooldridge234** [comment]
Fair enough! I'll see if I can get it working and if I do, I'll create a PR.

**Comment by jwooldridge234** [comment]
I'm not creating a PR because I haven't managed to make anything work properly yet. I got it to load by modifying the function like so:

```python
#Fetch the internal_embedding directory
        if self.is_sdxl :
          embedder = model.cond_stage_model
        else :
          embedder = model.cond_stage_model.wrapped

        internal_emb_dir = None
        if self.is_sd1: internal_emb_dir = embedder.transformer.text_model.embeddings
        elif self.is_sdxl : 
          cli_embedder = embedder.embedders[0]  # Accessing the first embedder

          if isinstance(cli_embedder, sd_hijack_clip.FrozenCLIPEmbedderForSDXLWithCustomWords):
              internal_emb_dir = cli_embedder.wrapped.transformer.text_model.embeddings # SDXL :Check if this works
        elif self.is_sd2 : internal_emb_dir = embedder.model
        
        internal_embs = internal_emb_dir.token_embedding.wrapped.weight # SDXL : See comment above

        ########
        if self.is_sd2 : #Fetch the tokenizer
          from modules.sd_hijack_open_clip import tokenizer as open_clip_tokenizer
          tokenizer = open_clip_tokenizer
        elif self.is_sdxl :
          cli_embedder = embedder.embedders[0]  # Accessing the first embedder

          if isinstance(cli_embedder, sd_hijack_clip.FrozenCLIPEmbedderForSDXLWithCustomWords):
              tokenizer = cli_embedder.wrapped.tokenizer # SDXL :Check if this works
        else : tokenizer = embedder.tokenizer
        #########
``` 
(Note: you have to import sd_hijack_clip from modules at the top of the file)

No idea if this is correct, but it does halfway function. However, it creates embeddings with a SD1.5 shape (768 size tensor vs the expected 2048 size tensor). They actually do work with SD1.5 models, producing distorted but still recognizable outputs.

If anyone's interested, here are my conclusions after messing about with this for a bit.

1. SDXL embeddings have a very different architecture to SD1.x or SD2.x embeddings. See this code from the updated modules/textual_inversion.py on the dev branch:

```python
elif type(data) == dict and 'clip_g' in data and 'clip_l' in data:  # SDXL embedding
          vec = {k: v.detach().to(devices.device, dtype=torch.float32) for k, v in data.items()}
          shape = data['clip_g'].shape[-1] + data['clip_l'].shape[-1]
          vectors = data['clip_g'].shape[0]
``` 

2. My code almost works. It outputs an embedding that is interpreted by the textual_inversion code as a SDXL embedding, having the two clip models in the data. However, the shape of the tensor is off. I'm not sure if that means it's really close to being correct or if it's going to require an entirely different method.

I'll keep trying and see if I can get anything working.

**Comment by Nekos4Lyfe** [comment]
Thank you for posting this. Very useful information. 

Embedding size can be found as the parameter "tools.size" in tools.py in the TokenMixer

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe I'm afraid I don't see a size parameter in tools.py, unless I'm missing something.

**Comment by Nekos4Lyfe** [comment]
Ah, sorry. You are correct. It's in the Data.py class. The vector size is initialized on line 783 in Data.py

I tokenize a the word "test" on line 782 and then use the dimensions of that vector to find the embedding size of the given model.

In the rest of the code (after initialization) you get vector size in each module by calling "self.data.vector.size"

It could be that SDXL uses a different tokenizer than SD 1.5 which is causing the problems. 

The Tokenizer is found in Tools.py as "Tools.tokenizer"

Feel free to ask any question you'd like here. It's still early access so we don't need to stick to the usual github formality.

**Comment by jwooldridge234** [comment]
Thanks! Didn't manage to make a breakthrough last night, but I got a little closer- I concatenated the tensors for both clip models, creating one tensor with 2048 dimensions, which passed the test for textual_inversion but fails on EmbeddingsWithFixes in sd_hijack. I ran a working SDXL embedding through and it turns out it isn't passing one 2048 tensors, it's sequentially passing two tensors of size 768 and then 1280. That's the size of the two embedders included in the model.

So if I'm getting this right, you have to encode the embedding with both embedders in such a way that it registers as one tensor of size 2048 for the purposes of textual_inversion and actually runs two embeddings through EmbeddingsWithFixes. Which seems... hard. Maybe I'm confused on something here though.

**Comment by jwooldridge234** [comment]
This is actually coming from the hijack def:

```python
for i in range(len(conditioner.embedders)):
                embedder = conditioner.embedders[i]
                typename = type(embedder).__name__
                if typename == 'FrozenOpenCLIPEmbedder':
                    embedder.model.token_embedding = EmbeddingsWithFixes(embedder.model.token_embedding, self)
                    conditioner.embedders[i] = sd_hijack_open_clip.FrozenOpenCLIPEmbedderWithCustomWords(embedder, self)
                    text_cond_models.append(conditioner.embedders[i])
                if typename == 'FrozenCLIPEmbedder':
                    model_embeddings = embedder.transformer.text_model.embeddings
                    model_embeddings.token_embedding = EmbeddingsWithFixes(model_embeddings.token_embedding, self)
                    conditioner.embedders[i] = sd_hijack_clip.FrozenCLIPEmbedderForSDXLWithCustomWords(embedder, self)
                    text_cond_models.append(conditioner.embedders[i])
                if typename == 'FrozenOpenCLIPEmbedder2':
                    embedder.model.token_embedding = EmbeddingsWithFixes(embedder.model.token_embedding, self, textual_inversion_key='clip_g')
                    conditioner.embedders[i] = sd_hijack_open_clip.FrozenOpenCLIPEmbedder2WithCustomWords(embedder, self)
                    text_cond_models.append(conditioner.embedders[i])
``` 

It runs through each of the embedders in the model and runs the EmbeddingsWithFixes code for each. So you end up with a size mismatch- the created embedding has 2048 dimensions while each of the embedders expects 768/1280. However, the textual_inversion code expects a single concatonated tensor. 

The fact that embeddings trained with kohya_ss are working means that it is possible to bridge the gap, just not sure how yet.

**Comment by jwooldridge234** [comment]
I'm seeing this in a correctly-formatted embedding file I downloaded from CivitAI:

```
{"clip_g":{"dtype":"F16","shape":[8,1280],"data_offsets":[0,20480]},"clip_l":{"dtype":"F16","shape":[8,768],"data_offsets":[20480,32768]}}
``` 

When I try to run the embedding through the Embedding Inspector tab, I get this error:

```
torch.Size([49408, 2048])
Traceback (most recent call last):
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/modules/embedding_inspector.py", line 119, in inspect
    emb_name, emb_id, emb_vec, loaded_emb = self.data.get_embedding_info(text)
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/extensions/TokenMixer/lib/data.py", line 603, in get_embedding_info
    emb_id = '['+ loaded_emb.checksum()+']' # emb_id is string for loaded embeddings
  File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 84, in checksum
    self.cached_checksum = f'{const_hash(self.vec.reshape(-1) * 100) & 0xffff:04x}'
AttributeError: 'dict' object has no attribute 'reshape'
``` 

I'm guessing (my knowledge of this is somewhat limited) SDXL embeddings are a dict containing two tensors, one for the clip_l encoder and one for the clip_g encoder. In order to save an embedding, you'd need to run the process twice using the two encoders and then save the dict as a .pt file.

I'm not sure I'm up to the task of actually building this, considering you'd probably need to completely refactor the code for the whole plugin, so I might just leave it here. Hopefully it's useful if/when you build out the SDXL code.

**Comment by Nekos4Lyfe** [comment]
Yes, I'd say you have done plenty. Great work! I'll move SDXL compatibility up on the agenda, but it will likely be a month or so until it is implemented.   Thanks again for all the help.

**Comment by jwooldridge234** [comment]
No worries! I had fun tinkering :) I'll keep an eye out for that!

**Comment by Nekos4Lyfe** [comment]
Hi Man! TokenMixer is now SDXL compatible! Still lot of stuff left so I will keep this page open, but I figured I send a message to let you know

**Comment by jwooldridge234** [comment]
Oh awesome! Going to check it out in a little bit :)

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe I think it's probably because I'm on Mac, but something about the embedding I just generated ("dog horse". saved with default settings as dghs001) causes issues at generation. It throws this even if I upcast the cross-attention layer to fp32. I didn't try no-half, because it slows generation to a crawl. I turned off all other extensions.

  7%|██▉                                         | 1/15 [00:06<01:34,  6.75s/it]
*** Error completing request                             | 0/15 [00:00<?, ?it/s]
*** Arguments: ('task(ospr2hjukd0x7z4)', 'photo of dghs001', '', [], 15, 'DPM++ 2M Karras', 1, 1, 7, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x2ac49f580>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/sd_samplers_cfg_denoiser.py", line 201, in forward
        devices.test_for_nans(x_out, "unet")
      File "/Users/jackwooldridge/StableDiffusion/stable-diffusion-webui/modules/devices.py", line 136, in test_for_nans
        raise NansException(message)
    modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

---

**Comment by Nekos4Lyfe** [comment]
Thanks for the info . I'll look into it

These were the settings I used for testing on A1111 today:
!python launch.py --share --opt-sub-quad-attention --disable-safe-unpickle --gradio-queue --no-half-vae

**Comment by jwooldridge234** [comment]
Sounds great. I tried those settings, but no luck.

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe Got it working- I just cast everything to "mps" and float16 and then modified line 247 of data.py to read "output = torch.cat([output.to(device = "mps" , dtype = torch.float16),current.to(device = "mps" , dtype = torch.float16)], dim=0)\" to resolve the issue with concatenating tensors on different devices. Not sure if that helps you when it comes to finding a universal solution, but it works as a messy local patch.

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe Just wanted to say thanks so much for this extension! I think it's honestly a must-have for SDXL. I was able to get so many concepts that the base model struggles with to work perfectly with very little effort.

**Comment by Nekos4Lyfe** [comment]
That makes me happy.  The github repo has now been updated to cast tensors to "mps" if such a device is available (i.e if the device is a MAC). Let me know if that works for you.

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe It works (after I altered data.py to cast the tensor concatenation to cpu before running numpy), but unfortunately I'm now getting embeds that don't look like the text entered at all.

**Comment by Nekos4Lyfe** [comment]
I see. Torch tends to behave strangely when values are sent from one device to another.

In the latest update I reverted it the device back to "cpu" for MAC users.

If you wish, you can fork over the github repo and test things on your end.
The choosen device can be found under the name "choosen_device" in the code

I will try running SDXL on float16 settings and see if I get similar problems , when I have the time.

Image below shows where choosen_device is located. There is no "shared" resource , instead they are currently just pasted at the top of the code for each relevant module. You can find all of them if you search "choosen_device" on the github search bar above. 

Data.py and everything in the toolbox are shared resources , while each module is standalone apart the vectors they pass to the Embedding generator (still called "TokenMixer.py" in the code). 

The embedding is saved in TokenMixer.py. 

![finalstep](https://github.com/Nekos4Lyfe/TokenMixer/assets/130230016/97f56b90-89b4-44b1-bc18-c941029a4067)
![choosendevice2](https://github.com/Nekos4Lyfe/TokenMixer/assets/130230016/80424617-be7a-42ba-9ad1-f670afaf7a6e)

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe Thanks! I'll see if I have time to mess around with it after work.

**Comment by jwooldridge234** [comment]
@Nekos4Lyfe Didn't end up having a chance to check, but just wanted to let you know you fixed the issue! :)

**Comment by Nekos4Lyfe** [comment]
What? How? I guess that's good news :D! 

I recommend you save this github version on your own device, just to to be on the safe side

**Comment by jwooldridge234** [comment]
Not sure, just pulled your latest and everything worked. I'll let you know if I see any other issues. And yeah, I've pulled it into a local branch.
